### ISSUE TITLE
Is `LIBCOMPILER_RT` a dependency?

### ISSUE THREAD

**Issue by razvand** [unikraft/lib-libunwind#1]
I'm able to build [app-helloworld-cpp](https://github.com/unikraft/app-helloworld-cpp) without the [lib-compiler-rt](https://github.com/unikraft/lib-compiler-rt) dependency currently configured in [Config.uk](https://github.com/unikraft/lib-libunwind/blob/staging/Config.uk#L4) and [Makefile.uk](https://github.com/unikraft/lib-libunwind/blob/staging/Makefile.uk#L41). Is it really required?

**Comment by nderjung** [comment]
Hey Razvan, are you using `kraft` to build the app?  If so, the KConfig option dependency is injected automatically.  To remove it, remove it from the `kraft.yaml` file.

**Comment by vladandrew** [comment]
Yes, you need some of the builtins from compiler-rt.
