### ISSUE TITLE
Change to UnwindRegistersSave.s?

### ISSUE THREAD

**Issue by anmolsahoo25** [unikraft/lib-libunwind#4]
Can someone please explain why this patch is applied - https://github.com/unikraft/lib-libunwind/blob/staging/patches/0001-Updated-the-RIP.patch

It seems to break exceptions and cause an access 0x0 due to this instruction - `movq %rbp, (%rax)`. I ran the helloworld-cpp template with exceptions and it gave an error. I am not sure I understand the exception handling implementation in unikraft, because even when I am handling an error it says exited with uncaught exception.

**Comment by razvand** [comment]
Hi, @anmolsahoo25 . Could you use [the `do-helloworld-cpp` script](https://github.com/unikraft-upb/scripts/blob/main/musl/README.md#app-helloworld-cpp) and tell us if your problem persists?

**Comment by eduardvintila** [comment]
Hey, @anmolsahoo25 @razvand. That instruction is, indeed, problematic. I have proposed a PR which should solve the issue: https://github.com/unikraft/lib-libunwind/pull/5

**Comment by anmolsahoo25** [comment]
Thank you!
